FastWork/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from user.views_user import *

urlpatterns = [
    path('admin/', admin.site.urls),

    # 首页
    url(r'^index/$', IndexView.as_view(), name='index'),

    # 用户管理
    url(r'^user/', include('user.urls', namespace='user')),

    # 权限管理
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),

    # 项目管理
    url(r'^project/', include('project.urls', namespace='project')),

    # 知识库管理
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),

    # 问题管理
    url(r'^issue/', include('issue.urls', namespace='issue')),

    # 站点地图
    url(r'^sitemap/', include('sitemap.urls', namespace='sitemap')),

    # 工具脚本
    url(r'^scripts/', include('scripts.urls', namespace='script')),

    # 工具执行
    url(r'^tools_execution/', include('tools_execution.urls', namespace='tools_execution')),

    # 文件仓库
    url(r'^file_depository/', include('file_depository.urls', namespace='file_depository')),

    # CMDB
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^agent/', include('agent.urls', namespace='agent')),

    # 定时任务
    url(r'^task_scheduler/', include('task_scheduler.urls', namespace='task_scheduler')),

    # 批量执行
    url(r'^batch_tasks/', include('batchTasks.urls', namespace='batch_tasks')),

    # 持续部署
    url(r'^deploy/', include('deploy.urls', namespace='deploy')),

    # 日志管理
    url(r'^journal/', include('journal.urls', namespace='journal')),

    # todoList
    url(r'^todoList/', include('todoList.urls', namespace='todoList')),

    url(r'^$', IndexView.as_view(), name='home'),
]

cmdb/urls.py
from django.conf.urls import url
from .views import *

app_name = "cmdb"

urlpatterns = [
    # cmdb
    url(r'assets/$', CmdbAssetsView.as_view(), name='cmdb-assets'),
    url(r'get_echart_datas/$', CmdbEchartDataView.as_view(), name='cmdb-echart-data'),
    url(r'get_server_infos/$', CmdbGetServerInfosView.as_view(), name='cmdb-get-server-infos'),
    url(r'get_server_infos/delete/$', CmdbDeleteView.as_view(), name='cmdb-get-server-infos-delete'),
    url(r'get_process/info/$', CmdbGetProcessInfoView.as_view(), name='cmdb-get-process-info'),
    url(r'get_server_infos/by/mac/$', CmdbGetServerInfoByMacView.as_view(), name='cmdb-get-server-infos-by-mac'),
    url(r'get_process/by/mac/$', CmdbGetProcessByMacView.as_view(), name='cmdb-get-process-infos-by-mac'),
    url(r'server/instance/details/$', CmdbServerInstanceDetailsView.as_view(),
        name='cmdb-get-server-infos-intance-details'),
    # 代码段管理
    url(r'code/segment/$', CmdbCodeSegmentView.as_view(), name='cmdb-code-segment'),
    url(r'code/segment/category/$', CmdbCodeSegmentCategoryView.as_view(), name='cmdb-code-segment-category'),
    url(r'code/segment/delete/$', CmdbCodeSegmentDeleteView.as_view(), name='cmdb-code-segment-delete'),
    url(r'code/segment/category/codesegement/$', CmdbCodeSegmentCodeSegementView.as_view(),
        name='cmdb-code-segment-category-codesegement'),
    url(r'code/segment/category/codesegement/add/$', CmdbCodeSegmentCodeSegementAddView.as_view(),
        name='cmdb-code-segment-category-codesegement-add'),
    url(r'code/segment/category/codesegement/edit/$', CmdbCodeSegmentCodeSegementEditView.as_view(),
        name='cmdb-code-segment-category-codesegement-edit'),
]

deploy/urls.py
from django.conf.urls import url
from .views import *

app_name = "deploy"

urlpatterns = [
    # 部署管理
    url(r'^programme/list/$', DeployTaskProgrammeListView.as_view(), name="deplot-programme-list"),
    url(r'^programme/edit/$', DeployTaskProgrammeEditView.as_view(), name="deplot-programme-edit"),
    url(r'^programme/remove/$', DeployTaskProgrammeRemoveView.as_view(), name="deplot-programme-remove"),
    # 部署任务记录
    url(r'^task/list/$', DeployTaskListView.as_view(), name="deplot-task-list"),
    url(r'^task/details/', DeployTaskeDetailsView.as_view(), name="deplot-task-details"),
    url(r'^task/add/$', task_deploy_add, name="deplot-task-add"),
    # Hook 持续交付
    url(r'^hook/template/', DeployTaskHookTemplateView.as_view(), name="deplot-hook-template"),
    url(r'^deploy/', deploy, name="deplot-deploy"),
]

project/urls.py
from django.conf.urls import url
from .views import *

app_name = "project"

urlpatterns = [
    url(r'^list/$', ProjectListView.as_view(), name="list"),
    url(r'^star/$', ProjectStarListView.as_view(), name='star'),
    url(r'^unstar/$', ProjectUnstarListView.as_view(), name='unstar'),
    url(r'^search/$', ProjectSearchView.as_view(), name='search'),
    # 项目概览
    url(r'^dashboard/$', ProjectDashboardView.as_view(), name="dashboard"),
    url(r'^dashboard/chart/$', ProjectDashboardChartView.as_view(), name="dashboard-chart"),

    # 数据统计
    url(r'^statistics/$', ProjectStatisticsView.as_view(), name="statistics"),
    url(r'^statistics/priority/$', ProjectStatisticsPriorityView.as_view(), name="statistics-priority"),
    url(r'^statistics/project/user/$', ProjectStatisticsProjectUserView.as_view(), name='statistics-project-user'),

    # 项目设置
    url(r'^settings/$', ProjectSettingsView.as_view(), name="settings"),
    url(r'^settings/delete/$', ProjectSettingsDeleteView.as_view(), name="settings-delete"),
    url(r'^settings/backup/$', ProjectSettingsBackupView.as_view(), name="settings-backup"),
    url(r'^settings/users/unbind/$', ProjectSettingsUsersUnbindView.as_view(), name="settings-users-unbind"),
    url(r'^settings/change/password/$', ProjectSettingsChangePasswordView.as_view(), name="settings-change-password"),
    url(r'^settings/invite/register/$', ProjectSettingsUsersRegisterView.as_view(), name="settings-invite-register"),
    url(r'^settings/modify/$', ProjectSettingsModifyView.as_view(), name="settings-modify"),
]

deploy/models.py
from django.db import models
from project.models import Project
from tools_execution.models import Accounts


class Programme(models.Model):
    """
    项目表
    """
    title = models.CharField(verbose_name="项目名", max_length=32)
    repo = models.CharField(verbose_name="仓库地址", max_length=128)
    env_choice = (
        ('prod', '正式环境'),
        ('test', '测试环境'),
    )
    env = models.CharField(verbose_name="环境", max_length=16, choices=env_choice, default="test")
    path = models.CharField(verbose_name="线上项目地址", max_length=128)
    server = models.ManyToManyField(verbose_name="关联服务器", to=Accounts)
    pj = models.ForeignKey(verbose_name="关联项目", to=Project, on_delete=models.CASCADE)

    def __str__(self):
        return "%s-%s" % (self.title, self.get_env_display())


class DeployTask(models.Model):
    """
    发布任务
    """
    # 项目名称+项目环境+tag+时间
    # eg：TestName-TestEnv-Tag-20200330
    uid = models.CharField(verbose_name="标识", max_length=64)
    programme = models.ForeignKey(verbose_name="项目环境", to="Programme", on_delete=models.CASCADE)
    tag = models.CharField(verbose_name="版本号", max_length=32)
    date = models.DateTimeField(auto_now_add=True, auto_created=True)
    status_choices = (
        (1, "待发布"),
        (2, "发布中"),
        (3, "发布完成"),
    )
    status = models.IntegerField(verbose_name="状态", choices=status_choices, default=1)
    before_download_script = models.TextField(verbose_name="下载前脚本", null=True, blank=True)
    after_download_script = models.TextField(verbose_name="下载后脚本", null=True, blank=True)
    before_deploy_script = models.TextField(verbose_name="发布前脚本", null=True, blank=True)
    after_deploy_script = models.TextField(verbose_name="发布后脚本", null=True, blank=True)
    pj = models.ForeignKey(verbose_name="关联项目", to=Project, on_delete=models.CASCADE)


class HookTemplate(models.Model):
    """
    存放钩子模版
    """
    title = models.CharField(verbose_name="标题", max_length=32)
    content = models.TextField(verbose_name="脚本内容")
    hook_type_choices = (
        (2, "下载前"),
        (4, "下载后"),
        (6, "发布前"),
        (8, "发布后"),
    )
    hook = models.IntegerField(verbose_name="钩子类型", choices=hook_type_choices)
    pj = models.ForeignKey(verbose_name="关联项目", to=Project, on_delete=models.CASCADE)


class Node(models.Model):
    task = models.ForeignKey(verbose_name="发布任务单", to=DeployTask, on_delete=models.CASCADE)
    text = models.CharField(verbose_name="节点文字", max_length=32)
    status_choices = (
        ("lightgray", "待发布"),
        ("green", "成功"),
        ("red", "失败"),
    )
    status = models.CharField(verbose_name="状态", max_length=16, choices=status_choices, default="lightgray")
    parent = models.ForeignKey(verbose_name="父节点", to="self", null=True, blank=True, on_delete=models.CASCADE)
    server = models.ForeignKey(verbose_name="服务器", to=Accounts, null=True, blank=True, on_delete=models.CASCADE)
    execute_records = models.TextField(verbose_name="节点执行记录", null=True, blank=True)

deploy/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic.base import View
from django.http import JsonResponse, HttpResponse
from deploy.models import *
from batchTasks.models import *
from . import forms


class DeployTaskListView(View):
    def get(self, request):
        programme_id = request.GET.get("programme_id")
        project_id = request.GET.get("project_id")
        programme_object = Programme.objects.filter(id=programme_id, pj_id=project_id).first()
        task_list = DeployTask.objects.filter(programme_id=programme_id, pj_id=project_id).all().order_by("-id")
        return render(request, 'deploy/task_list.html', locals())


class DeployTaskeDetailsView(View):
    def get(self, request):
        project_id = request.GET.get("project_id")
        id = request.GET.get("id")
        task = DeployTask.objects.filter(id=id, pj_id=project_id).first()
        task_obj = DeployTask.objects.filter(id=id, pj_id=project_id).all()
        return render(request, 'deploy/task_list_details.html', locals())


# 添加发布
def task_deploy_add(request):
    programme_id = request.GET.get("programme_id")
    project_id = request.GET.get("project_id")
    programme_object = Programme.objects.filter(id=programme_id, pj_id=project_id).first()
    if request.method == "GET":
        form = forms.DeployTaskModelForm(programme_object, project_id)
        return render(request, 'deploy/task_form.html', locals())

    form = forms.DeployTaskModelForm(programme_object, project_id, data=request.POST)
    if form.is_valid():
        form.save()
        # 接受参数，反向映射地址
        return redirect("/deploy/task/list/?project_id={}&programme_id={}".format(project_id, programme_id))
    return render(request, 'deploy/task_form.html', locals())


class DeployTaskProgrammeListView(View):
    def get(self, request):
        project_id = request.GET.get("project_id")
        projects = Programme.objects.filter(pj_id=project_id).all()
        accounts_obj = Accounts.objects.filter(project_id=project_id).all()
        return render(request, 'deploy/projects_list.html', locals())

    def post(self, request):
        operation_type = request.POST.get("operation_type")
        project_id = request.POST.get("project_id")

        if operation_type == "edit":
            project_name = request.POST.get("project_name")
            project_address_online = request.POST.get("project_address_online")
            programmeUpdateObj = Programme.objects.filter(pj_id=project_id).update(
                title=project_name, path=project_address_online
            )
            if programmeUpdateObj:
                data = {
                    'state': 0,
                    'data': "修改成功!"
                }
                return JsonResponse(data)
            else:
                data = {
                    'state': 127,
                    'data': "修改失败!"
                }
                return JsonResponse(data)

        if operation_type == "add":
            proj_name = request.POST.get("proj_name")
            proj_address_online = request.POST.get("proj_address_online")
            proj_data_dir = request.POST.get("proj_data_dir")
            proj_env = request.POST.get("proj_env")
            # 192.168.1.1,192.168.1.2,
            proj_server_list = request.POST.get("proj_server_list")
            obj = Programme.objects.create(
                title=proj_name,
                repo=proj_address_online,
                env=proj_env,
                path=proj_data_dir,
                pj_id=project_id,
            )
            servers = proj_server_list.split(",")
            for ser in servers:
                if ser:
                    ser_obj = Accounts.objects.filter(hostname=ser, project_id=project_id).first()
                    obj.server.add(ser_obj.id)
            data = {
                'state': 0,
                'data': "创建成功!"
            }
            return JsonResponse(data)


class DeployTaskProgrammeEditView(View):
    def get(self, request):
        project_id = request.GET.get("project_id")
        programme_id = request.GET.get("programme_id")
        project_obj = Programme.objects.filter(pj_id=project_id, pk=programme_id).first()
        projects = Programme.objects.filter(id=programme_id, pj_id=project_id).all()
        servers = []
        for line in projects:
            for x_line in line.server.all():
                servers.append(x_line.hostname)
        data = {
            "project_id": project_obj.pk,
            "project_name": project_obj.title.strip(),
            "project_address": project_obj.repo,
            "project_env": project_obj.env,
            "project_address_online": project_obj.path,
            "project_server": servers,
        }
        return JsonResponse({'status': True, 'data': data})


class DeployTaskProgrammeRemoveView(View):
    def get(self, request):
        project_id = request.GET.get("project_id")
        programme_id = request.GET.get("programme_id")
        project_obj = Programme.objects.filter(pj_id=project_id, pk=programme_id).first()
        project_obj.delete()
        return JsonResponse({
            "status": True,
            "msg": "删除工程成功!"
        })


class DeployTaskHookTemplateView(View):
    def get(self, request):
        hid = request.GET.get("hid")
        project_id = request.GET.get("project_id")
        if hid == "0":
            return JsonResponse({"status": True, "content": None})
        hook_template_obj = HookTemplate.objects.filter(id=hid, pj_id=project_id).first()
        return JsonResponse({"status": True, "content": hook_template_obj.content})


# 部署
def deploy(request):
    project_id = request.GET.get("project_id")
    taskid = request.GET.get("taskid")
    programme_id = request.GET.get("programme_id")
    task_obj = DeployTask.objects.filter(id=taskid, pj_id=project_id, programme_id=programme_id).first()
    node_obj = Node.objects.filter(task_id=taskid, text="开始").first()
    node_objs = Node.objects.filter(task_id=taskid).all()
    results = {}
    try:
        if node_obj.status == "lightgray":
            # 等于灰色，说明初始化了，但是未部署
            results["status"] = "unfinished_deploy"
        else:
            results["status"] = "finished_deploy"
    except:
        # print("未初始化")
        results["status"] = "unfinished_init"
    return render(request, 'deploy/deploy.html', locals())

templates/deploy/task_list.html
{% extends 'base/site-base.html' %}
{% load static %}
{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}
{% block title %}
    FastWork - {{ programme_object.title }} - 发布历史记录
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'deploy:deplot-programme-list' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">工程列表</a></li>
                    <li class="active">{{ programme_object.title }}-{{ programme_object.get_env_display }} / 发布任务
                    </li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div class="col-lg-6">
                <div class="input-group">
                    <a class="btn btn-default" style="margin-bottom: 5px;color: black"
                       href="{% url 'deploy:deplot-task-add' %}?project_id={{ request.tracer.project.id }}&programme_id={{ programme_object.id }}">
                        <i class="fa fa-plus" aria-hidden="true"></i> 新增发布
                    </a>
                </div>
            </div>

        </div>

        <div class="col-sm-12">
            <div class="container-fluid">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div>
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th style="text-align: center">ID</th>
                                    <th>标识</th>
                                    <th style="text-align: center">创建时间</th>
                                    <th style="text-align: center">状态</th>
                                    <th style="text-align: center">项目配置</th>
                                    <th style="text-align: center">操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for task in task_list %}
                                    <tr>
                                        <th style="text-align: center">{{ task.id }}</th>
                                        <th>{{ task.uid }}</th>
                                        <th style="text-align: center">{{ task.date }}</th>
                                        {% if task.status == 1 %}
                                            <th style="text-align: center">
                                                <span class="label label-info">待发布</span>
                                            </th>
                                        {% elif task.status == 2 %}
                                            <th style="text-align: center">
                                                <span class="label label-warning">发布中</span>
                                            </th>
                                        {% else %}
                                            <th style="text-align: center">
                                                <span class="label label-success">发布完成</span>
                                            </th>
                                        {% endif %}

                                        <th style="text-align: center"><a
                                                href="{% url 'deploy:deplot-task-details' %}?project_id={{ request.tracer.project.id }}&id={{ task.id }}"
                                                class="btn btn-default"
                                                style="font-size: 11px;color: black">
                                            <i class="fa fa-eye"> 查看配置</i>
                                        </a></th>
                                        <th style="text-align: center">
                                            <a href="{% url 'deploy:deplot-deploy' %}?project_id={{ request.tracer.project.id }}&programme_id={{ programme_object.id }}&taskid={{ task.id }}"
                                               class="btn btn-default"
                                               style="font-size: 11px;color: black">
                                                <i class="fa fa-send"> 去发布</i>
                                            </a>
                                        </th>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/deploy/task_list_details.html
{% extends 'base/site-base.html' %}
{% load static %}

{% block css %}
{% endblock %}
{% block title %}
    FastWork - 部署管理
{% endblock %}
{% block content %}
    <div class="container-fluid" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li>
                        <a href="{% url 'deploy:deplot-task-list' %}?project_id={{ request.tracer.project.id }}&programme_id={{ task.programme_id }}"
                           style="color: #337ab7">发布历史</a></li>
                    <li class="active">{{ task.uid }} / 部署配置记录</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="container-fluid">
                <div class="panel panel-default">
                    <div class="panel-body">


                        <table class="table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>项目</th>
                                <th>版本</th>
                                <th>发布情况</th>
                                <th>下载前脚本内容</th>
                                <th>下载后脚本内容</th>
                                <th>发布前脚本内容</th>
                                <th>发布后脚本内容</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="info">
                                {% for foo in task_obj %}
                                    <td>{{ foo.pk }}</td>
                                    <td>{{ foo.programme.title }}</td>
                                    <td>{{ foo.tag }}</td>
                                    <td>{{ foo.get_status_display }}</td>
                                    {% if foo.before_download_script %}
                                        <td>{{ foo.before_download_script }}</td>
                                    {% else %}
                                        <td>无定义</td>
                                    {% endif %}

                                    {% if foo.after_download_script %}
                                        <td>{{ foo.after_download_script }}</td>
                                    {% else %}
                                        <td>无定义</td>
                                    {% endif %}


                                    {% if foo.before_deploy_script %}
                                        <td>{{ foo.before_deploy_script }}</td>
                                    {% else %}
                                        <td>无定义</td>
                                    {% endif %}


                                    {% if foo.after_deploy_script %}
                                        <td>{{ foo.after_deploy_script }}</td>
                                    {% else %}
                                        <td>无定义</td>
                                    {% endif %}

                                {% endfor %}
                            </tr>
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}