FastWork/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from user.views_user import *

urlpatterns = [
    path('admin/', admin.site.urls),

    # 首页
    url(r'^index/$', IndexView.as_view(), name='index'),

    # 用户管理
    url(r'^user/', include('user.urls', namespace='user')),

    # 权限管理
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),

    # 项目管理
    url(r'^project/', include('project.urls', namespace='project')),

    # 知识库管理
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),

    # 问题管理
    url(r'^issue/', include('issue.urls', namespace='issue')),

    # 站点地图
    url(r'^sitemap/', include('sitemap.urls', namespace='sitemap')),

    # 工具脚本
    url(r'^scripts/', include('scripts.urls', namespace='script')),

    # 工具执行
    url(r'^tools_execution/', include('tools_execution.urls', namespace='tools_execution')),

    # 文件仓库
    url(r'^file_depository/', include('file_depository.urls', namespace='file_depository')),

    # CMDB
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^agent/', include('agent.urls', namespace='agent')),

    # 定时任务
    url(r'^task_scheduler/', include('task_scheduler.urls', namespace='task_scheduler')),

    # 批量执行
    url(r'^batch_tasks/', include('batchTasks.urls', namespace='batch_tasks')),

    # 持续部署
    url(r'^deploy/', include('deploy.urls', namespace='deploy')),

    # 日志管理
    url(r'^journal/', include('journal.urls', namespace='journal')),

    # todoList
    url(r'^todoList/', include('todoList.urls', namespace='todoList')),

    url(r'^$', IndexView.as_view(), name='home'),
]

cmdb/urls.py
from django.conf.urls import url
from .views import *

app_name = "cmdb"

urlpatterns = [
    # cmdb
    url(r'assets/$', CmdbAssetsView.as_view(), name='cmdb-assets'),
    url(r'get_echart_datas/$', CmdbEchartDataView.as_view(), name='cmdb-echart-data'),
    url(r'get_server_infos/$', CmdbGetServerInfosView.as_view(), name='cmdb-get-server-infos'),
    url(r'get_server_infos/delete/$', CmdbDeleteView.as_view(), name='cmdb-get-server-infos-delete'),
    url(r'get_process/info/$', CmdbGetProcessInfoView.as_view(), name='cmdb-get-process-info'),
    url(r'get_server_infos/by/mac/$', CmdbGetServerInfoByMacView.as_view(), name='cmdb-get-server-infos-by-mac'),
    url(r'get_process/by/mac/$', CmdbGetProcessByMacView.as_view(), name='cmdb-get-process-infos-by-mac'),
    url(r'server/instance/details/$', CmdbServerInstanceDetailsView.as_view(),
        name='cmdb-get-server-infos-intance-details'),
    # 代码段管理
    url(r'code/segment/$', CmdbCodeSegmentView.as_view(), name='cmdb-code-segment'),
    url(r'code/segment/category/$', CmdbCodeSegmentCategoryView.as_view(), name='cmdb-code-segment-category'),
    url(r'code/segment/delete/$', CmdbCodeSegmentDeleteView.as_view(), name='cmdb-code-segment-delete'),
    url(r'code/segment/category/codesegement/$', CmdbCodeSegmentCodeSegementView.as_view(),
        name='cmdb-code-segment-category-codesegement'),
    url(r'code/segment/category/codesegement/add/$', CmdbCodeSegmentCodeSegementAddView.as_view(),
        name='cmdb-code-segment-category-codesegement-add'),
    url(r'code/segment/category/codesegement/edit/$', CmdbCodeSegmentCodeSegementEditView.as_view(),
        name='cmdb-code-segment-category-codesegement-edit'),
]

project/urls.py
from django.conf.urls import url
from .views import *

app_name = "project"

urlpatterns = [
    url(r'^list/$', ProjectListView.as_view(), name="list"),
    url(r'^star/$', ProjectStarListView.as_view(), name='star'),
    url(r'^unstar/$', ProjectUnstarListView.as_view(), name='unstar'),
    url(r'^search/$', ProjectSearchView.as_view(), name='search'),
    # 项目概览
    url(r'^dashboard/$', ProjectDashboardView.as_view(), name="dashboard"),
    url(r'^dashboard/chart/$', ProjectDashboardChartView.as_view(), name="dashboard-chart"),

    # 数据统计
    url(r'^statistics/$', ProjectStatisticsView.as_view(), name="statistics"),
    url(r'^statistics/priority/$', ProjectStatisticsPriorityView.as_view(), name="statistics-priority"),
    url(r'^statistics/project/user/$', ProjectStatisticsProjectUserView.as_view(), name='statistics-project-user'),

    # 项目设置
    url(r'^settings/$', ProjectSettingsView.as_view(), name="settings"),
    url(r'^settings/delete/$', ProjectSettingsDeleteView.as_view(), name="settings-delete"),
    url(r'^settings/backup/$', ProjectSettingsBackupView.as_view(), name="settings-backup"),
    url(r'^settings/users/unbind/$', ProjectSettingsUsersUnbindView.as_view(), name="settings-users-unbind"),
    url(r'^settings/change/password/$', ProjectSettingsChangePasswordView.as_view(), name="settings-change-password"),
    url(r'^settings/invite/register/$', ProjectSettingsUsersRegisterView.as_view(), name="settings-invite-register"),
    url(r'^settings/modify/$', ProjectSettingsModifyView.as_view(), name="settings-modify"),
]

rbac/urls.py
from django.conf.urls import url
from rbac import views_role, views_menu
from user import views_user, views_structure

app_name = "rbac"

urlpatterns = [
    # 组织架构的改删查操作
    url(r'^structure/$', views_structure.StructureView.as_view(), name="structure"),
    url(r'^structure/list$', views_structure.StructureListView.as_view(), name="structure-list"),
    url(r'^structure/detail$', views_structure.StructureDetailView.as_view(), name="structure-detail"),
    url(r'^structure/delete$', views_structure.StructureDeleteView.as_view(), name="structure-delete"),
    url(r'^structure/add_user$', views_structure.Structure2UserView.as_view(), name="structure-add_user"),

    # 角色管理
    url(r'^role/$', views_role.RoleView.as_view(), name="role"),
    url(r'^role/list$', views_role.RoleListView.as_view(), name="role-list"),
    url(r'^role/detail$', views_role.RoleDetailView.as_view(), name="role-detail"),
    url(r'^role/delete$', views_role.RoleDeleteView.as_view(), name="role-delete"),
    url(r'^role/role_menu$', views_role.Role2MenuView.as_view(), name="role-role_menu"),
    url(r'^role/role_menu_list$', views_role.Role2MenuListView.as_view(), name="role-role_menu_list"),
    url(r'^role/role_user$', views_role.Role2UserView.as_view(), name="role-role_user"),

    # 菜单管理
    url(r'^menu/$', views_menu.MenuView.as_view(), name="menu"),
    url(r'^menu/list$', views_menu.MenuListView.as_view(), name="menu-list"),
    url(r'^menu/detail$', views_menu.MenuListDetailView.as_view(), name="menu-detail"),
    url(r'^menu/delete$', views_menu.MenuListDeleteView.as_view(), name="menu-delete"),

    # 用户管理
    url(r'^user/$', views_user.UserView.as_view(), name="user"),
    url(r'^user/list$', views_user.UserListView.as_view(), name="user-list"),
    url(r'^user/detail$', views_user.UserDetailView.as_view(), name="user-detail"),
    url(r'^user/update$', views_user.UserUpdataView.as_view(), name="user-update"),
    url(r'^user/create$', views_user.UserCreateView.as_view(), name="user-create"),
    url(r'^user/delete$', views_user.UserDeleteView.as_view(), name="user-delete"),
    url(r'^user/enable$', views_user.UserEnableView.as_view(), name="user-enable"),
    url(r'^user/disable$', views_user.UserDisableView.as_view(), name="user-disable"),
    url(r'^user/adminpasswdchange$', views_user.AdminPasswdChangeView.as_view(), name="user-adminpasswdchange"),

    #首次登录分配权限页面
    url(r'^admin/page/$', views_role.AdminPageView.as_view(), name="admin-page"),
    url(r'^admin/page/bind/$', views_role.AdminPageBindView.as_view(), name="admin-page-bind"),

]

rbac/models.py
from django.db import models


class Menu(models.Model):
    """
    菜单
    """
    title = models.CharField(max_length=32, unique=True, verbose_name="菜单名")
    parent = models.ForeignKey("self", null=True, blank=True, verbose_name="父菜单", on_delete=models.CASCADE)
    is_top = models.BooleanField(default=False, verbose_name="首页显示")
    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name="图标")
    code = models.CharField(max_length=50, null=True, blank=True, verbose_name="编码")
    url = models.CharField(max_length=128, unique=True, null=True, blank=True)

    def __str__(self):
        title_list = [self.title]
        p = self.parent
        while p:
            title_list.insert(0, p.title)
            p = p.parent
        return '-'.join(title_list)

    class Meta:
        verbose_name = "菜单"
        verbose_name_plural = verbose_name

    @classmethod
    def getMenuByRequestUrl(self, url):
        ret = dict(menu=Menu.objects.get(url=url))
        return ret


class Role(models.Model):
    """
    角色：绑定权限
    """
    title = models.CharField(max_length=32)
    permissions = models.ManyToManyField("menu", blank=True)

    def __str__(self):
        return self.title

    def create_role_permissions(self, menu_id):
        self.permissions = menu_id
        self.save()

    class Meta:
        verbose_name = "角色"
        verbose_name_plural = verbose_name

rbac/forms.py
from django import forms
from .models import Menu, Role


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'


class RoleForm(forms.ModelForm):
    class Meta:
        model = Role
        fields = '__all__'

rbac/views.py
from django.shortcuts import render

# Create your views here.

templates/rbac/admin-page.html
{% extends 'base/without_project_base.html' %}
{% load static %}
{% block title %}
    管理员面板
{% endblock %}

{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}"
                           style="color: #337ab7">项目大厅</a></li>
                    <li class="active">管理员面板</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="">
            <div class="container-fluid">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <strong>说明!</strong> 平台首次初始化，需先执行[root@localhost tools]#/Users/chenweiyong/ENVS/fastwork/bin/python3 tools/init_before_use_fastwork.py之后，在此绑定：角色和菜单【超管&所有菜单】、角色和用户【超管&管理员账号】。
                        </div>
                    </div>
                    <hr>
                    <div class="panel-body">
                        <div class="wrapper wrapper-content animated fadeInRight">
                            <div class="wrapper wrapper-content">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <label for="">角色</label>

                                        <select class="form-control" name="type" id="selected_role">
                                            <option id="selected_role"
                                                    value={{ structure.type }}> {{ structure.get_type_display|default:"--选择角色--" }} </option>

                                            {% for foo in objects_all %}
                                                <option id="selected_role"
                                                        value="{{ foo.title }}">{{ foo.title }}</option>
                                            {% endfor %}
                                        </select>

                                        <label for="">菜单</label>
                                        <select class="form-control" name="type" id="selected_menu" multiple
                                                style="height: 200px">
                                            {% for foo in menu_objects_all %}
                                                <option id="selected_menu"
                                                        value="{{ foo.id }}">{{ foo.title }}</option>
                                            {% endfor %}
                                        </select>

                                        <button type="button" id="bind_role_menu" class="btn btn-primary"
                                                data-dismiss="modal" style="background-color: #167be0;margin-top: 10px">
                                            角色绑定菜单
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="panel-body">
                        <div class="wrapper wrapper-content animated fadeInRight">
                            <div class="wrapper wrapper-content">
                                <div class="row">

                                    <div class="col-sm-12">
                                        <label for="">角色</label>

                                        <select class="form-control" name="type" id="selected_user_role">
                                            <option id="selected_user_role"
                                                    value={{ structure.type }}> {{ structure.get_type_display|default:"--选择角色--" }} </option>

                                            {% for foo in objects_all %}
                                                <option id="selected_user_role"
                                                        value="{{ foo.title }}">{{ foo.title }}</option>
                                            {% endfor %}
                                        </select>

                                        <label for="">用户</label>
                                        <select class="form-control" name="type" id="selected_user">
                                            <option id="selected_user"
                                                    value={{ structure.type }}> {{ structure.get_type_display|default:"--选择用户--" }} </option>
                                            {% for foo in objects_all__exclude %}
                                                <option id="selected_user"
                                                        value="{{ foo.id }}">{{ foo.username }}</option>
                                            {% endfor %}
                                        </select>

                                        <button type="button" id="bind_user_role" class="btn btn-primary"
                                                data-dismiss="modal" style="background-color: #167be0;margin-top: 10px">
                                            角色绑定用户
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
        $("#bind_role_menu").click(function () {
            //公用参数
            var selected_role_index = document.getElementById("selected_role").selectedIndex;
            var selected_role = document.getElementById("selected_role").options[selected_role_index].text;

            o = document.getElementById("selected_menu");
            var intvalue = "";
            for (i = 0; i < o.length; i++) {
                if (o.options[i].selected) {
                    intvalue += o.options[i].value + ",";
                }
            }

            var selected_menu = intvalue.substr(0, intvalue.length - 1)


            if (selected_role === "--选择角色--" || selected_menu === "") {
                alert("必填项不能为空");
                return false;
            } else {
                $.ajax({
                    url: "{% url 'rbac:admin-page' %}",
                    type: "POST",
                    dataType: 'json',
                    data: {
                        'selected_role': selected_role,
                        'selected_menu': selected_menu,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (data) {
                        if (data.status === 200) {
                            alert(data.msg);
                            location.href = "{% url 'rbac:admin-page' %}"
                        } else {
                            alert(data.msg)
                        }
                    }
                })
            }

        })
        $("#bind_user_role").click(function () {
            //公用参数
            var selected_user_role_index = document.getElementById("selected_user_role").selectedIndex;
            var selected_user_role = document.getElementById("selected_user_role").options[selected_user_role_index].text;

            var selected_user_index = document.getElementById("selected_user").selectedIndex;
            var selected_user = document.getElementById("selected_user").options[selected_user_index].text;

            if (selected_user_role === "--选择角色--" || selected_user === "--选择用户--") {
                alert("必填项不能为空");
                return false;
            } else {
                $.ajax({
                    url: "{% url 'rbac:admin-page-bind' %}",
                    type: "POST",
                    dataType: 'json',
                    data: {
                        'selected_user_role': selected_user_role,
                        'selected_user': selected_user,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (data) {
                        if (data.status === 200) {
                            alert(data.msg);
                            location.href = "{% url 'rbac:admin-page' %}"
                        } else {
                            alert(data.msg)
                        }
                    }
                })
            }

        })
    </script>
{% endblock %}

templates/rbac/menu-list.html
{% extends 'base/without_project_base.html' %}
{% load static %}
{% block title %}
    菜单管理
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'rbac/css/jquery.dataTables.min.css' %}">
    <link href="{% static 'layui/2.8.7/layui.css' %}" rel="stylesheet">
    <style>

        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }

        .damacontent {
            filter: blur(3px);
        }

        .choose {
            border-left: 2px solid #f90 !important;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}"
                           style="color: #337ab7">项目大厅</a></li>
                    <li class="active">权限中心</li>
                    <li class="active">菜单管理</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="">
            <div class="container-fluid">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="wrapper wrapper-content animated fadeInRight">
                            <div class="wrapper wrapper-content">

                                <div class="col-sm-3">
                                    <div class="panel panel-default">
                                        <div class="panel-heading"
                                             style="background-color:transparent;font-weight: bold;">
                                            菜单管理
                                        </div>
                                        <div class="list-group" style="border-radius: 0">
                                            <div>
                                                <a href="{% url 'rbac:user' %}"
                                                   class="list-group-item">用户管理</a>
                                                <a href="{% url 'rbac:menu' %}"
                                                   class="choose list-group-item">菜单管理</a>
                                                <a href="{% url 'rbac:structure' %}"
                                                   class="list-group-item">组织管理</a>
                                                <a href="{% url 'rbac:role' %}"
                                                   class="list-group-item">角色管理</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-9">
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><i class="fa fa-address-card-o"
                                                                      aria-hidden="true"></i> 菜单管理
                                        </div>
                                        <div class="panel-body">


                                            <div class="box-header" style="margin-bottom: 40px">
                                                <div class="btn-group pull-left">
                                                    <button type="button" id="btnRefresh" onclick="refresh()"
                                                            class="btn btn-success btn-sm">
                                                        <i class="glyphicon glyphicon-repeat"></i>刷新
                                                    </button>
                                                </div>
                                                <div class="btn-group pull-left">&nbsp</div>
                                                <div class="btn-group pull-left">
                                                    <button type="button" id="btnCreate"
                                                            class="btn btn-primary btn-sm">
                                                        <i class="glyphicon glyphicon-plus"></i>新增
                                                    </button>
                                                </div>
                                            </div>
                                            <table id="dtbList" class="display" cellspacing="0" style="margin-top: 10px"
                                                   width="100%">
                                                <thead>
                                                <tr valign="middle">
                                                    <th><input type="checkbox" id="checkAll"></th>
                                                    <th>ID</th>
                                                    <th>名称</th>
                                                    <th>代码</th>
                                                    <th>url</th>
                                                    <th>首页显示</th>
                                                    <th>父菜单</th>
                                                    <th>操作</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>


                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'rbac/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'rbac/js/dataTables.const.js' %}"></script>
    <script src="{% static 'layui/2.8.7/layui.js' %}"></script>

    <!-- iCheck 1.0.1 -->
    <script type="text/javascript">
        $(function () {
            $('#SYSTEM-RBAC').addClass('active');
            $('#SYSTEM-RBAC-MENU').addClass('active');

        });
    </script>

    <script type="text/javascript">
        var oDataTable = null;
        $(function () {
            oDataTable = initTable();

            function initTable() {
                var oTable = $('#dtbList').DataTable($.extend(true, {},
                    DATATABLES_CONSTANT.DATA_TABLES.DEFAULT_OPTION,
                    {
                        ajax: {
                            "url": "{% url 'rbac:menu-list' %}",
                            "data": function (d) {
                                //d.select=$("#select").val();
                            }
                        },
                        columns: [
                            DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,
                            {
                                data: "id",
                                width: "5%",
                            },
                            {
                                data: "title",
                            },
                            {
                                data: "code",
                            },
                            {
                                data: "url",
                            },
                            {
                                data: "is_top",
                            },

                            {
                                data: "parent__title",
                            },
                            {
                                data: "id",
                                bSortable: "false",
                                render: function (data, type, row, meta) {
                                    var ret = "";
                                    var ret = "<button title='详情-编辑' onclick='doUpdate("
                                        + data + ")'><i class='glyphicon glyphicon-pencil btn-sm'></i></button>";
                                    ret = ret + "<button title='删除' onclick='doDelete("
                                        + data + ")'><i class='glyphicon glyphicon-trash btn-sm'></i></button>";
                                    return ret;
                                }
                            }
                        ],
                    }));
                return oTable;
            }

            //checkbox全选
            $("#checkAll").on("click", function () {
                if ($(this).prop("checked") === true) {
                    $("input[name='checkList']").prop("checked", $(this).prop("checked"));
                    $('#example tbody tr').addClass('selected');
                } else {
                    $("input[name='checkList']").prop("checked", false);
                    $('#example tbody tr').removeClass('selected');
                }
            });


            $("#btnRefresh").click(function () {
                oDataTable.ajax.reload();
            });

            $("#btnCreate").click(function () {
                layer.open({
                    type: 2,
                    title: '新增',
                    shadeClose: false,
                    maxmin: true,
                    area: ['800px', '400px'],
                    content: "{% url 'rbac:menu-detail' %}",
                    end: function () {
                        //关闭时做的事情
                        oDataTable.ajax.reload();
                    }
                });
            });

        });

        function doUpdate(id) {
            layer.open({
                type: 2,
                title: '编辑',
                shadeClose: false,
                maxmin: true,
                area: ['800px', '400px'],
                content: ["{% url 'rbac:menu-detail' %}" + '?id=' + id, 'no'],
                end: function () {
                    //关闭时做的事情
                    window.location.reload();
                }
            });
        }

        //删除单个数据
        function doDelete(id) {
            layer.alert('确定删除吗？', {
                title: '提示'
                , icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
                , time: 0 //不自动关闭
                , btn: ['YES', 'NO']
                , yes: function (index) {
                    layer.close(index);
                    $.ajax({
                        type: "POST",
                        url: "{% url 'rbac:menu-delete' %}",
                        data: {"id": id, csrfmiddlewaretoken: '{{ csrf_token }}'},  //防止post数据时报 csrf_token 403
                        cache: false,
                        success: function (msg) {
                            if (msg.result) {
                                layer.alert('删除成功', {icon: 1});
                                oDataTable.ajax.reload();
                            } else {
                                //alert(msg.message);
                                layer.alert('删除失败', {icon: 2});
                            }
                            return;
                        }
                    });
                }
            });

        }


    </script>

    <script>
        function refresh() {
            window.location.reload()
        }
    </script>
{% endblock %}