FastWork/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from user.views_user import *

urlpatterns = [
    path('admin/', admin.site.urls),

    # 首页
    url(r'^index/$', IndexView.as_view(), name='index'),

    # 用户管理
    url(r'^user/', include('user.urls', namespace='user')),

    # 权限管理
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),

    # 项目管理
    url(r'^project/', include('project.urls', namespace='project')),

    # 知识库管理
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),

    # 问题管理
    url(r'^issue/', include('issue.urls', namespace='issue')),

    # 站点地图
    url(r'^sitemap/', include('sitemap.urls', namespace='sitemap')),

    # 工具脚本
    url(r'^scripts/', include('scripts.urls', namespace='script')),

    # 工具执行
    url(r'^tools_execution/', include('tools_execution.urls', namespace='tools_execution')),

    # 文件仓库
    url(r'^file_depository/', include('file_depository.urls', namespace='file_depository')),

    # CMDB
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^agent/', include('agent.urls', namespace='agent')),

    # 定时任务
    url(r'^task_scheduler/', include('task_scheduler.urls', namespace='task_scheduler')),

    # 批量执行
    url(r'^batch_tasks/', include('batchTasks.urls', namespace='batch_tasks')),

    # 持续部署
    url(r'^deploy/', include('deploy.urls', namespace='deploy')),

    # 日志管理
    url(r'^journal/', include('journal.urls', namespace='journal')),

    # todoList
    url(r'^todoList/', include('todoList.urls', namespace='todoList')),

    url(r'^$', IndexView.as_view(), name='home'),
]

cmdb/urls.py
from django.conf.urls import url
from .views import *

app_name = "cmdb"

urlpatterns = [
    # cmdb
    url(r'assets/$', CmdbAssetsView.as_view(), name='cmdb-assets'),
    url(r'get_echart_datas/$', CmdbEchartDataView.as_view(), name='cmdb-echart-data'),
    url(r'get_server_infos/$', CmdbGetServerInfosView.as_view(), name='cmdb-get-server-infos'),
    url(r'get_server_infos/delete/$', CmdbDeleteView.as_view(), name='cmdb-get-server-infos-delete'),
    url(r'get_process/info/$', CmdbGetProcessInfoView.as_view(), name='cmdb-get-process-info'),
    url(r'get_server_infos/by/mac/$', CmdbGetServerInfoByMacView.as_view(), name='cmdb-get-server-infos-by-mac'),
    url(r'get_process/by/mac/$', CmdbGetProcessByMacView.as_view(), name='cmdb-get-process-infos-by-mac'),
    url(r'server/instance/details/$', CmdbServerInstanceDetailsView.as_view(),
        name='cmdb-get-server-infos-intance-details'),
    # 代码段管理
    url(r'code/segment/$', CmdbCodeSegmentView.as_view(), name='cmdb-code-segment'),
    url(r'code/segment/category/$', CmdbCodeSegmentCategoryView.as_view(), name='cmdb-code-segment-category'),
    url(r'code/segment/delete/$', CmdbCodeSegmentDeleteView.as_view(), name='cmdb-code-segment-delete'),
    url(r'code/segment/category/codesegement/$', CmdbCodeSegmentCodeSegementView.as_view(),
        name='cmdb-code-segment-category-codesegement'),
    url(r'code/segment/category/codesegement/add/$', CmdbCodeSegmentCodeSegementAddView.as_view(),
        name='cmdb-code-segment-category-codesegement-add'),
    url(r'code/segment/category/codesegement/edit/$', CmdbCodeSegmentCodeSegementEditView.as_view(),
        name='cmdb-code-segment-category-codesegement-edit'),
]

journal/urls.py
from django.conf.urls import url
from journal.views import *

app_name = "journal"
urlpatterns = [
    # 日志管理中心
    url(r'^logs/center/$', LogsManagementView.as_view(), name="journal-logs_management"),
    # 文件分发日志
    url(r'^logs/center/file_send/$', LogsCenterFileSendView.as_view(), name="journal-logs_file_send"),
    # 定时任务执行日志
    url(r'^logs/center/scheduler/$', LogsCenterSchedulerView.as_view(), name="journal-logs_scheduler"),
    # 用户登录日志
    url(r'^logs/center/user_login/$', LogsCenterUserLoginView.as_view(), name="journal-logs_user_login"),
    # webssh日志
    url(r'^logs/center/webssh/$', LogsCenterWebsshView.as_view(), name="journal-logs_webssh"),
    # 项目部署日志
    url(r'^logs/center/deploy/$', LogsCenterDeployView.as_view(), name="journal-logs_deploy"),
    # 工具库部署日志
    url(r'^logs/center/tools/$', LogsCenterToolsView.as_view(), name="journal-logs_tools"),
]

project/urls.py
from django.conf.urls import url
from .views import *

app_name = "project"

urlpatterns = [
    url(r'^list/$', ProjectListView.as_view(), name="list"),
    url(r'^star/$', ProjectStarListView.as_view(), name='star'),
    url(r'^unstar/$', ProjectUnstarListView.as_view(), name='unstar'),
    url(r'^search/$', ProjectSearchView.as_view(), name='search'),
    # 项目概览
    url(r'^dashboard/$', ProjectDashboardView.as_view(), name="dashboard"),
    url(r'^dashboard/chart/$', ProjectDashboardChartView.as_view(), name="dashboard-chart"),

    # 数据统计
    url(r'^statistics/$', ProjectStatisticsView.as_view(), name="statistics"),
    url(r'^statistics/priority/$', ProjectStatisticsPriorityView.as_view(), name="statistics-priority"),
    url(r'^statistics/project/user/$', ProjectStatisticsProjectUserView.as_view(), name='statistics-project-user'),

    # 项目设置
    url(r'^settings/$', ProjectSettingsView.as_view(), name="settings"),
    url(r'^settings/delete/$', ProjectSettingsDeleteView.as_view(), name="settings-delete"),
    url(r'^settings/backup/$', ProjectSettingsBackupView.as_view(), name="settings-backup"),
    url(r'^settings/users/unbind/$', ProjectSettingsUsersUnbindView.as_view(), name="settings-users-unbind"),
    url(r'^settings/change/password/$', ProjectSettingsChangePasswordView.as_view(), name="settings-change-password"),
    url(r'^settings/invite/register/$', ProjectSettingsUsersRegisterView.as_view(), name="settings-invite-register"),
    url(r'^settings/modify/$', ProjectSettingsModifyView.as_view(), name="settings-modify"),
]

scripts/urls.py
from django.conf.urls import url
from .views import *

app_name = "scripts"

urlpatterns = [
    # 工具库
    url(r'^all/$', ScriptsAllView.as_view(), name="scripts-all"),
    url(r'^detail/$', ScriptsDetailView.as_view(), name='scripts-detail'),
    url(r'^add/$', ScriptsAddView.as_view(), name="scripts-add"),
    url(r'^auto/add/$', ScriptsAutoAddView.as_view(), name="scripts-auto-add"),
    url(r'^edit/$', ScriptsEditView.as_view(), name="scripts-edit"),
    url(r'^search/$', ScriptsSearchView.as_view(), name="scripts-search"),
    url(r'^search/output/$', ScriptsSearchOutputView.as_view(), name="scripts-search-output"),
    url(r'^delete/$', ScriptsDeleteView.as_view(), name="scripts-delete"),
    url(r'^download/$', ScriptsDownloadView.as_view(), name="scripts-download"),
    url(r'^export/output/$', ScriptsExportOutputView.as_view(), name="scripts-export-output"),
    # 分类管理
    url(r'^category/add/$', ScriptsCategoryAddView.as_view(), name="scripts-category-add"),
    url(r'^category/search/$', ScriptsCategorySearchView.as_view(), name="scripts-category-search"),
    url(r'^information/edit/$', ScriptsInformationEditView.as_view(), name="scripts-information-edit"),

    url(r'^invite/url/$', ScriptsInviteUrlView.as_view(), name='scripts-url'),
    url(r'^invite/join/script/$', ScriptsInviteJoinView.as_view(), name='scripts-invite-join'),
    url(r'^invite/join/script/download/$', ScriptsInviteJoinDownloadView.as_view(),
        name='scripts-invite-join-download'),
]

templates/logs/log_center.html
{% extends 'base/site-base.html' %}
{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block title %}
    FastWork - 日志中心
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'journal:journal-logs_management' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">日志中心</a></li>
                    <li class="active">分模块日志中心</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div class="col-sm-12">
                <div class="jumbotron">
                    <p style="font-size: 25px;">用户登录日志中心</p>
                    <p style="color: gray">记录了包括用户登录的登录状态、登录时间、用户角色等...</p>
                    <p><a class="btn btn-primary"
                          href="{% url 'journal:journal-logs_user_login' %}?project_id={{ request.tracer.project.id }}"
                          role="button"
                          style="background-color: #167be0;color: white;border: none">
                        <span class="glyphicon glyphicon-facetime-video"></span>点击查看
                    </a></p>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="jumbotron">
                    <p style="font-size: 25px">WebSSH日志中心</p>
                    <p style="color: gray">记录了包括WebSSH登录之后的执行命令、执行结果等...</p>
                    <p><a class="btn btn-primary"
                          href="{% url 'journal:journal-logs_webssh' %}?project_id={{ request.tracer.project.id }}"
                          role="button"
                          style="background-color: #167be0;color: white;border: none">
                        <span class="glyphicon glyphicon-facetime-video"></span>点击查看
                    </a></p>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="jumbotron">
                    <p style="font-size: 25px">定时任务日志中心</p>
                    <p style="color: gray">记录了包括定时任务的执行时间、执行命令、执行状态、执行结果等...</p>
                    <p><a class="btn btn-primary"
                          href="{% url 'journal:journal-logs_scheduler' %}?project_id={{ request.tracer.project.id }}"
                          role="button"
                          style="background-color: #167be0;color: white;border: none">
                        <span class="glyphicon glyphicon-facetime-video"></span>点击查看
                    </a></p>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="jumbotron">
                    <p style="font-size: 25px">工具库日志中心</p>
                    <p style="color: gray">记录了包括定时任务的执行时间、执行状态、执行结果等...</p>
                    <p><a class="btn btn-primary"
                          href="{% url 'journal:journal-logs_tools' %}?project_id={{ request.tracer.project.id }}"
                          role="button"
                          style="background-color: #167be0;color: white;border: none">
                        <span class="glyphicon glyphicon-facetime-video"></span>点击查看
                    </a></p>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="jumbotron">
                    <p style="font-size: 25px">文件分发日志中心</p>
                    <p style="color: gray">记录了包括文件分发的分发时间、分发文件、分发结果等...</p>
                    <p><a class="btn btn-primary"
                          href="{% url 'journal:journal-logs_file_send' %}?project_id={{ request.tracer.project.id }}"
                          role="button"
                          style="background-color: #167be0;color: white;border: none">
                        <span class="glyphicon glyphicon-facetime-video"></span>点击查看
                    </a></p>
                </div>
            </div>

            <div class="col-sm-12">
                <div class="jumbotron">
                    <p style="font-size: 25px">项目部署日志中心</p>
                    <p style="color: gray">记录了包括项目部署的工程信息、部署状态、部署结果详情等...</p>
                    <p><a class="btn btn-primary"
                          href="{% url 'journal:journal-logs_deploy' %}?project_id={{ request.tracer.project.id }}"
                          role="button"
                          style="background-color: #167be0;color: white;border: none">
                        <span class="glyphicon glyphicon-facetime-video"></span>点击查看
                    </a></p>
                </div>
            </div>


        </div>

    </div>

{% endblock %}

templates/logs/logs_deploy.html
{% extends 'base/site-base.html' %}
{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block title %}
    FastWork - 项目部署日志中心
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'journal:journal-logs_management' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">日志中心</a></li>
                    <li class="active">项目部署日志中心</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">序号</th>
                        <th scope="col">所属项目</th>
                        <th scope="col">所属工程</th>
                        <th scope="col">工程代码地址</th>
                        <th scope="col">工程部署路径</th>
                        <th scope="col">部署任务名称</th>
                        <th scope="col">部署任务建立日期</th>
                        <th scope="col">部署任务发布节点名称</th>
                        <th scope="col">部署任务发布节点状态</th>
                        <th scope="col">部署任务发布节点至服务器</th>
                        <th scope="col">部署任务发布节点执行结果</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for res in results %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <th scope="row"><span class="label label-success">{{ res.project_name }}+</span>
                            </th>
                            <td>{{ res.programme_name }}</td>
                            <td>{{ res.programme_repo }}</td>
                            <td>{{ res.programme_path }}</td>
                            <td>{{ res.deploy_task_name }}</td>
                            <td>{{ res.deploy_task_date }}</td>
                            <td>{{ res.deploy_task_node_text }}</td>
                            {#                            <td>{{ res.deploy_task_node_status }}</td>#}
                            {% if res.deploy_task_node_status == "green" %}
                                <th scope="row"><span class="label label-success"
                                                      style="background-color: #5cb85c;border: none">执行成功</span>
                                </th>
                            {% elif res.deploy_task_node_status == "red" %}
                                <th scope="row"><span class="label label-danger"
                                                      style="background-color: red;border: none">执行失败</span></th>
                            {% elif res.deploy_task_node_status == "lightgray" %}
                                <th scope="row"><span class="label label-info"
                                                      style="background-color: lightgray;border: none">暂未发布</span>
                                </th>
                            {% endif %}
                            {% if res.deploy_task_node_server %}
                                <td>{{ res.deploy_task_node_server }}</td>
                            {% else %}
                                <td>未设置部署服务器</td>
                            {% endif %}
                            <td>{{ res.deploy_task_node_execute_records }}</td>

                            {#                            <th scope="row"><span class="label label-success">{{ file_send_obj.project.name }}+</span>#}
                            {#                            </th>#}

                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/logs/logs_file_send.html
{% extends 'base/site-base.html' %}
{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block title %}
    FastWork - 文件分发日志中心
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'journal:journal-logs_management' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">日志中心</a></li>
                    <li class="active">文件分发日志</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">序号</th>
                        <th scope="col">包裹单号</th>
                        <th scope="col">分发时间</th>
                        <th scope="col">文件名称</th>
                        <th scope="col">操作人</th>
                        <th scope="col">分发结果</th>
                        <th scope="col">所属项目</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for file_send_obj in file_send_objs %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ file_send_obj.name }}</td>
                            <td>{{ file_send_obj.create_datetime }}</td>
                            <td>{{ file_send_obj.file.name }}</td>
                            <td>{{ file_send_obj.creator.username }}</td>
                            <td>{{ file_send_obj.records }}</td>
                            <th scope="row"><span class="label label-success">{{ file_send_obj.project.name }}+</span>
                            </th>

                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/logs/logs_scheduler.html
{% extends 'base/site-base.html' %}
{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block title %}
    FastWork - 定时任务日志中心
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'journal:journal-logs_management' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">日志中心</a></li>
                    <li class="active">定时任务日志中心</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">序号</th>
                        <th scope="col">任务ID</th>
                        <th scope="col">执行时间</th>
                        <th scope="col">执行动作</th>
                        <th scope="col">执行结果</th>
                        <th scope="col">状态</th>
                        <th scope="col">所属项目</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for scheduler_obj in scheduler_objs %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ scheduler_obj.task_id }}</td>
                            <td>{{ scheduler_obj.exe_time }}</td>
                            <td>{{ scheduler_obj.cmd }}</td>
                            <td>{{ scheduler_obj.stdout }}</td>
                            <td>{{ scheduler_obj.status }}</td>
                            <th><span class="label label-success">{{ scheduler_obj.project.name }}+</span></th>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/logs/logs_tools.html
{% extends 'base/site-base.html' %}
{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block title %}
    FastWork - 工具库日志中心
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'journal:journal-logs_management' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">日志中心</a></li>
                    <li class="active">工具库日志中心</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">序号</th>
                        <th scope="col">执行类型</th>
                        <th scope="col">执行环境</th>
                        <th scope="col">执行目标</th>
                        <th scope="col">执行工具</th>
                        <th scope="col">执行时间</th>
                        <th scope="col">执行人</th>
                        <th scope="col">执行命令</th>
                        <th scope="col">所属项目</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for toollog in toolLogs %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ toollog.target }}</td>
                            <td>{{ toollog.env }}</td>
                            <th><span class="label label-warning">{{ toollog.server }}</span></th>
                            {% if toollog.script == "批量操作模块专用" %}
                                <td><a disabled style="color: gray;text-decoration: none">{{ toollog.script }}</a></td>
                            {% else %}
                                <td><a target="_blank"
                                       href="{% url 'script:scripts-detail' %}?project_id={{ toollog.project.id }}&script_id={{ toollog.script_id }}">{{ toollog.script }}</a>
                                </td>
                            {% endif %}
                            <td>{{ toollog.date }}</td>
                            <td>{{ toollog.creator }}</td>
                            <td>{{ toollog.content }}</td>
                            <th><span class="label label-success">{{ toollog.project.name }}+</span></th>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/logs/logs_user_login.html
{% extends 'base/site-base.html' %}
{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block title %}
    FastWork - 用户登录日志中心
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'journal:journal-logs_management' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">日志中心</a></li>
                    <li class="active">用户登录日志中心</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">序号</th>
                        <th scope="col">用户名</th>
                        <th scope="col">登录时间</th>
                        <th scope="col">是否管理员</th>
                        <th scope="col">邮箱</th>
                        <th scope="col">登录结果</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user_login_obj in user_login_objs %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ user_login_obj.username }}</td>
                            <td>{{ user_login_obj.last_login }}</td>
                            <td>{{ user_login_obj.is_superuser }}</td>
                            <td>{{ user_login_obj.email }}</td>
                            {% if user_login_obj.isSuccess == "登录成功" %}
                                <th scope="row"><span
                                        class="label label-success">{{ user_login_obj.isSuccess }}</span></th>
                            {% else %}
                                <th scope="row"><span
                                        class="label label-danger">{{ user_login_obj.isSuccess }}</span></th>
                            {% endif %}
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/logs/logs_webssh.html
{% extends 'base/site-base.html' %}
{% block css %}
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block title %}
    FastWork - WebSSH日志中心
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'journal:journal-logs_management' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">日志中心</a></li>
                    <li class="active">WebSSH日志中心</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                    <tr>

                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td style="font-size: 20px;text-align: center">
                            WebSSH日志,请去该项目【logs】目录下查看以【*.webssh.command.log】的日志文件
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}