FastWork/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from user.views_user import *

urlpatterns = [
    path('admin/', admin.site.urls),

    # 首页
    url(r'^index/$', IndexView.as_view(), name='index'),

    # 用户管理
    url(r'^user/', include('user.urls', namespace='user')),

    # 权限管理
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),

    # 项目管理
    url(r'^project/', include('project.urls', namespace='project')),

    # 知识库管理
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),

    # 问题管理
    url(r'^issue/', include('issue.urls', namespace='issue')),

    # 站点地图
    url(r'^sitemap/', include('sitemap.urls', namespace='sitemap')),

    # 工具脚本
    url(r'^scripts/', include('scripts.urls', namespace='script')),

    # 工具执行
    url(r'^tools_execution/', include('tools_execution.urls', namespace='tools_execution')),

    # 文件仓库
    url(r'^file_depository/', include('file_depository.urls', namespace='file_depository')),

    # CMDB
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^agent/', include('agent.urls', namespace='agent')),

    # 定时任务
    url(r'^task_scheduler/', include('task_scheduler.urls', namespace='task_scheduler')),

    # 批量执行
    url(r'^batch_tasks/', include('batchTasks.urls', namespace='batch_tasks')),

    # 持续部署
    url(r'^deploy/', include('deploy.urls', namespace='deploy')),

    # 日志管理
    url(r'^journal/', include('journal.urls', namespace='journal')),

    # todoList
    url(r'^todoList/', include('todoList.urls', namespace='todoList')),

    url(r'^$', IndexView.as_view(), name='home'),
]

cmdb/urls.py
from django.conf.urls import url
from .views import *

app_name = "cmdb"

urlpatterns = [
    # cmdb
    url(r'assets/$', CmdbAssetsView.as_view(), name='cmdb-assets'),
    url(r'get_echart_datas/$', CmdbEchartDataView.as_view(), name='cmdb-echart-data'),
    url(r'get_server_infos/$', CmdbGetServerInfosView.as_view(), name='cmdb-get-server-infos'),
    url(r'get_server_infos/delete/$', CmdbDeleteView.as_view(), name='cmdb-get-server-infos-delete'),
    url(r'get_process/info/$', CmdbGetProcessInfoView.as_view(), name='cmdb-get-process-info'),
    url(r'get_server_infos/by/mac/$', CmdbGetServerInfoByMacView.as_view(), name='cmdb-get-server-infos-by-mac'),
    url(r'get_process/by/mac/$', CmdbGetProcessByMacView.as_view(), name='cmdb-get-process-infos-by-mac'),
    url(r'server/instance/details/$', CmdbServerInstanceDetailsView.as_view(),
        name='cmdb-get-server-infos-intance-details'),
    # 代码段管理
    url(r'code/segment/$', CmdbCodeSegmentView.as_view(), name='cmdb-code-segment'),
    url(r'code/segment/category/$', CmdbCodeSegmentCategoryView.as_view(), name='cmdb-code-segment-category'),
    url(r'code/segment/delete/$', CmdbCodeSegmentDeleteView.as_view(), name='cmdb-code-segment-delete'),
    url(r'code/segment/category/codesegement/$', CmdbCodeSegmentCodeSegementView.as_view(),
        name='cmdb-code-segment-category-codesegement'),
    url(r'code/segment/category/codesegement/add/$', CmdbCodeSegmentCodeSegementAddView.as_view(),
        name='cmdb-code-segment-category-codesegement-add'),
    url(r'code/segment/category/codesegement/edit/$', CmdbCodeSegmentCodeSegementEditView.as_view(),
        name='cmdb-code-segment-category-codesegement-edit'),
]

project/urls.py
from django.conf.urls import url
from .views import *

app_name = "project"

urlpatterns = [
    url(r'^list/$', ProjectListView.as_view(), name="list"),
    url(r'^star/$', ProjectStarListView.as_view(), name='star'),
    url(r'^unstar/$', ProjectUnstarListView.as_view(), name='unstar'),
    url(r'^search/$', ProjectSearchView.as_view(), name='search'),
    # 项目概览
    url(r'^dashboard/$', ProjectDashboardView.as_view(), name="dashboard"),
    url(r'^dashboard/chart/$', ProjectDashboardChartView.as_view(), name="dashboard-chart"),

    # 数据统计
    url(r'^statistics/$', ProjectStatisticsView.as_view(), name="statistics"),
    url(r'^statistics/priority/$', ProjectStatisticsPriorityView.as_view(), name="statistics-priority"),
    url(r'^statistics/project/user/$', ProjectStatisticsProjectUserView.as_view(), name='statistics-project-user'),

    # 项目设置
    url(r'^settings/$', ProjectSettingsView.as_view(), name="settings"),
    url(r'^settings/delete/$', ProjectSettingsDeleteView.as_view(), name="settings-delete"),
    url(r'^settings/backup/$', ProjectSettingsBackupView.as_view(), name="settings-backup"),
    url(r'^settings/users/unbind/$', ProjectSettingsUsersUnbindView.as_view(), name="settings-users-unbind"),
    url(r'^settings/change/password/$', ProjectSettingsChangePasswordView.as_view(), name="settings-change-password"),
    url(r'^settings/invite/register/$', ProjectSettingsUsersRegisterView.as_view(), name="settings-invite-register"),
    url(r'^settings/modify/$', ProjectSettingsModifyView.as_view(), name="settings-modify"),
]

scripts/urls.py
from django.conf.urls import url
from .views import *

app_name = "scripts"

urlpatterns = [
    # 工具库
    url(r'^all/$', ScriptsAllView.as_view(), name="scripts-all"),
    url(r'^detail/$', ScriptsDetailView.as_view(), name='scripts-detail'),
    url(r'^add/$', ScriptsAddView.as_view(), name="scripts-add"),
    url(r'^auto/add/$', ScriptsAutoAddView.as_view(), name="scripts-auto-add"),
    url(r'^edit/$', ScriptsEditView.as_view(), name="scripts-edit"),
    url(r'^search/$', ScriptsSearchView.as_view(), name="scripts-search"),
    url(r'^search/output/$', ScriptsSearchOutputView.as_view(), name="scripts-search-output"),
    url(r'^delete/$', ScriptsDeleteView.as_view(), name="scripts-delete"),
    url(r'^download/$', ScriptsDownloadView.as_view(), name="scripts-download"),
    url(r'^export/output/$', ScriptsExportOutputView.as_view(), name="scripts-export-output"),
    # 分类管理
    url(r'^category/add/$', ScriptsCategoryAddView.as_view(), name="scripts-category-add"),
    url(r'^category/search/$', ScriptsCategorySearchView.as_view(), name="scripts-category-search"),
    url(r'^information/edit/$', ScriptsInformationEditView.as_view(), name="scripts-information-edit"),

    url(r'^invite/url/$', ScriptsInviteUrlView.as_view(), name='scripts-url'),
    url(r'^invite/join/script/$', ScriptsInviteJoinView.as_view(), name='scripts-invite-join'),
    url(r'^invite/join/script/download/$', ScriptsInviteJoinDownloadView.as_view(),
        name='scripts-invite-join-download'),
]

scripts/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic.base import View
from utils.encrypt import uid
from scripts.models import *
from django.http import JsonResponse, HttpResponse
from django.db.models import Q
from user.models import UserProfile
import uuid
from django.utils.encoding import smart_str, escape_uri_path
from django.conf import settings
from utils import dabao
import os


class ScriptsInviteUrlView(View):
    def get(self, request):
        project_id = request.GET.get("project_id")
        scripts_id = request.GET.get("script_id")
        code = uid(scripts_id)
        ShareThings.objects.create(
            project_id=project_id,
            script_id=scripts_id,
            code=code,
            creator=request.tracer.user
        )

        # 将验邀请码返回给前端，前端页面上展示出来。
        url = "{scheme}://{host}{path}".format(
            scheme=request.scheme,
            host=request.get_host(),
            path='/script/invite/join/script/?code={}'.format(code)
        )
        return JsonResponse({'status': True, 'data': url})


class ScriptsAllView(View):
    def get(self, request):
        project_id = request.GET.get("project_id")
        categroy_count = []
        categories = ToolsCategory.objects.filter(Q(project_id=project_id) | Q(project_id=1)).all()
        for category in categories:
            count = Scripts.objects.filter(project_id=project_id, tool_category_id=category.id).count()
            data = {
                "category": category,
                "count": count
            }
            categroy_count.append(data)
        scripts_obj = Scripts.objects.filter(project_id=project_id).all()
        return render(request, 'scripts/scripts_list.html', locals())


class ScriptsDetailView(View):
    def get(self, request):
        project_id = request.GET.get("project_id")
        scripts_id = request.GET.get("script_id")
        try:
            from tools_execution.models import Accounts
            comment = Scripts.objects.filter(id=scripts_id, project_id=project_id).first()
            accounts_obj = Accounts.objects.filter(project_id=project_id).all()
            categories = ToolsCategory.objects.filter(Q(project_id=project_id) | Q(project_id=1)).all()
            categroy_count = []
            for category in categories:
                count = Scripts.objects.filter(project_id=project_id, tool_category_id=category.id).count()
                data = {
                    "category": category,
                    "count": count
                }
                categroy_count.append(data)
            return render(request, 'scripts/scripts_details_by_channels.html', locals())
        except:
            return JsonResponse({
                "code": 127,
                "script_id": scripts_id,
                "message": 'get script detail failed, may the script has gone away.'
            })


class ScriptsAddView(View):
    def get(self, request):
        project_id = request.GET.get("project_id")
        wiki_object = Wiki.objects.filter(project_id=project_id).all()
        return render(request, 'scripts/scripts_mirror_add.html', locals())

    def post(self, request):
        project_id = request.POST.get("project_id")
        tools_title = request.POST.get("tools_title").strip()
        tools_desc = request.POST.get("tools_desc").strip()
        language = request.POST.get("scripts_type").strip()
        selected_wiki = request.POST.get("selected_wiki").strip()
        content = request.POST.get("content")
        user_obj = UserProfile.objects.filter(username=request.tracer.user.username).first()
        if language == "python":
            # 说明该项目下有文档内容
            if selected_wiki != "notwiki":
                wiki_obj = Wiki.objects.filter(title=selected_wiki).first()
                obj = Scripts.objects.create(
                    title=tools_title,
                    content=content,
                    desc=tools_desc,
                    project_id=project_id,
                    wiki_id=wiki_obj.id,
                    suffix="py",
                    creator=user_obj,
                    tool_category_id=ToolsCategory.objects.filter(name="默认").first().pk,

                )
                if obj:
                    ret = {
                        "state": 0,
                        "msg": "create script success",
                    }
                    return JsonResponse(ret)
                else:
                    ret = {
                        "state": 127,
                        "msg": "create script failed",
                    }
                    return JsonResponse(ret)
            # 说明该项目下还未有文档内容
            else:
                obj = Scripts.objects.create(
                    title=tools_title,
                    content=content,
                    desc=tools_desc,
                    project_id=project_id,
                    suffix="py",
                    creator=user_obj,
                    tool_category_id=ToolsCategory.objects.filter(name="默认").first().pk
                )
                if obj:
                    ret = {
                        "state": 0,
                        "msg": "create script success",
                    }
                    return JsonResponse(ret)
                else:
                    ret = {
                        "state": 127,
                        "msg": "create script failed",
                    }
                    return JsonResponse(ret)

        elif language == "shell":
            # 说明该项目下有文档内容
            if selected_wiki != "notwiki":
                wiki_obj = Wiki.objects.filter(title=selected_wiki).first()
                obj = Scripts.objects.create(
                    title=tools_title,
                    content=content,
                    desc=tools_desc,
                    project_id=project_id,
                    wiki_id=wiki_obj.id,
                    suffix="sh",
                    showImage="/static/img/shell.png",
                    creator=user_obj,
                    tool_category_id=ToolsCategory.objects.filter(name="默认").first().pk

                )
                if obj:
                    ret = {
                        "state": 0,
                        "msg": "create script success",
                    }
                    return JsonResponse(ret)
                else:
                    ret = {
                        "state": 127,
                        "msg": "create script failed",
                    }
                    return JsonResponse(ret)
            # 说明该项目下还未有文档内容
            else:
                obj = Scripts.objects.create(
                    title=tools_title,
                    content=content,
                    desc=tools_desc,
                    project_id=project_id,
                    suffix="sh",
                    showImage="/static/img/shell.png",
                    creator=user_obj,
                    tool_category_id=ToolsCategory.objects.filter(name="默认").first().pk
                )
                if obj:
                    ret = {
                        "state": 0,
                        "msg": "create script success",
                    }
                    return JsonResponse(ret)
                else:
                    ret = {
                        "state": 127,
                        "msg": "create script failed",
                    }
                    return JsonResponse(ret)

        elif language == "java":
            # 说明该项目下有文档内容
            if selected_wiki != "notwiki":
                wiki_obj = Wiki.objects.filter(title=selected_wiki).first()
                obj = Scripts.objects.create(
                    title=tools_title,
                    content=content,
                    desc=tools_desc,
                    project_id=project_id,
                    wiki_id=wiki_obj.id,
                    suffix="java",
                    showImage="/static/img/java.png",
                    creator=user_obj,
                    tool_category_id=ToolsCategory.objects.filter(name="默认").first().pk

                )
                if obj:
                    ret = {
                        "state": 0,
                        "msg": "create script success",
                    }
                    return JsonResponse(ret)
                else:
                    ret = {
                        "state": 127,
                        "msg": "create script failed",
                    }
                    return JsonResponse(ret)
            # 说明该项目下还未有文档内容
            else:
                obj = Scripts.objects.create(
                    title=tools_title,
                    content=content,
                    desc=tools_desc,
                    project_id=project_id,
                    suffix="java",
                    showImage="/static/img/java.png",
                    creator=user_obj,
                    tool_category_id=ToolsCategory.objects.filter(name="默认").first().pk
                )
                if obj:
                    ret = {
                        "state": 0,
                        "msg": "create script success",
                    }
                    return JsonResponse(ret)
                else:
                    ret = {
                        "state": 127,
                        "msg": "create script failed",
                    }
                    return JsonResponse(ret)

        elif language == "go":
            # 说明该项目下有文档内容
            if selected_wiki != "notwiki":
                wiki_obj = Wiki.objects.filter(title=selected_wiki).first()
                obj = Scripts.objects.create(
                    title=tools_title,
                    content=content,
                    desc=tools_desc,
                    project_id=project_id,
                    wiki_id=wiki_obj.id,
                    suffix="go",
                    showImage="/static/img/go.png",
                    creator=user_obj,

templates/scripts/script_search_output.html
{% extends 'base/site-base.html' %}
{% load static %}


{% block title %}
    FastWork - 工具库导出
{% endblock %}

{% block css %}
    {#    <link rel="stylesheet" href="/global_css/script_search_output.css">#}
    {#        <link rel="stylesheet" href="/static/global_css/scripts_list.css">#}
    <link rel="stylesheet" href="{% static 'global_css/output_all_scripts.css' %}">


{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">
        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'script:scripts-all' %}?project_id={{ request.tracer.project.id }}">工具库</a>
                    </li>
                    <li class="active">工具导出</li>
                </ol>
            </div>
        </div>


        <div class="col-sm-12" style="margin-top: -20px">
            <form method="post" action="{% url 'script:scripts-search' %}?project_id={{ request.tracer.project.id }}"
                  style="transform: scale(1.0)">
                {% csrf_token %}
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="checkbox" onclick="checkAll(this)" id="all"
                               style="width: 15px;height: 15px;"/><span style="font-size: 15px">全选</span>

                        <input class="btn btn-primary btn-xs" type="button" onclick="selValue()" value="一键导出"
                               style="margin-left: 10px;margin-top: -5px">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-12">
            {% if scripts_obj %}
                <div>
                    <div class="panel-body">

                        {% for foo in scripts_obj %}
                            <div class="item" style="margin-left: 30px">

                                <div style="height: 30px;text-align: center;padding: 10px 10px;color: #8c8c8c;background-color: #f5f5f5;overflow: scroll">
                                    <span title="{{ foo.title }}">{{ foo.title }}</span>
                                </div>

                                <a href="{% url 'script:scripts-detail' %}?project_id={{ request.tracer.project.id }}&script_id={{ foo.id }}"
                                   class="title">
                                    <img src="{{ foo.showImage }}" alt="">
                                </a>

                                <hr>

                                <div style="height: 30px;padding: 10px 10px;color: #8c8c8c;overflow: scroll">
                                    {% if foo.desc %}
                                        <span title="{{ foo.desc }}"><small>说明：{{ foo.desc }}</small></span>
                                    {% else %}
                                        <span title="{{ foo.desc }}"><small>说明：暂无说明</small></span>
                                    {% endif %}
                                </div>
                                <input type="checkbox" name="box"
                                       style="border:none;margin:0 auto;width: 15px;height: 15px;margin-top: -10px;float: right"
                                       value="{{ foo.id }}">
                            </div>
                        {% endfor %}

                    </div>
                </div>
            {% else %}
                <div style="height:calc(100vh - 100px)">
                    <div style="text-align: center;margin-top: 200px">
                            <span style="text-align: center;font-size: 15px">暂无工具，请点击
                            <a class="btn btn-primary btn-sm" style="background-color: #167be0"
                               href="{% url 'script:scripts-add' %}?project_id={{ request.tracer.project.id }}"><span
                                    class="glyphicon glyphicon-plus"
                                    aria-hidden="true"></span> 新建工具</a>
                                创建
                            </span>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
        //全选
        function checkAll(obj) {
            //获取name=box的复选框
            var boxs = document.getElementsByName("box");
            for (var i = 0; i < boxs.length; i++) {
                boxs[i].checked = obj.checked;
            }
        }

        //获取选中的值
        function selValue() {
            var valArr = [];
            var boxs = document.getElementsByName("box");
            for (var i = 0; i < boxs.length; i++) {
                if (boxs[i].checked == true) {
                    valArr[i] = boxs[i].value;
                }
            }
            var vals = valArr.join(',');
            if (vals === '') {
                alert("请选择需要导出的工具")
                return
            }
            $.ajax({
                url: "{% url 'script:scripts-export-output' %}?project_id={{ request.tracer.project.id }}",
                type: "POST",
                dataType: "json",
                data: {
                    "value": vals,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (data) {
                    download(data.url)
                }
            })
        };

        // 直接下载，用户体验好
        function download(url) {
            var $form = $('<form method="GET"></form>');
            $form.attr('action', url);
            $form.appendTo($('body'));
            $form.submit();
        }
    </script>


{% endblock %}

templates/scripts/scripts_category_depository.html
{% extends 'base/site-base.html' %}
{% load static %}


{% block title %}
    FastWork - 工具库
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/global_css/scripts_list.css">
    <style>
        .content {
            height: calc(100vh - 120px);
            overflow: scroll;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid content" style="margin-top: 20px">

        <div class="col-sm-12">
            <div class="panel-heading">
                <ol class="breadcrumb">
                    <li><a href="{% url 'project:list' %}" style="color: #337ab7">项目大厅</a></li>
                    <li><a href="{% url 'script:scripts-all' %}?project_id={{ request.tracer.project.id }}"
                           style="color: #337ab7">工具库</a></li>
                    <li class="active">工具分类列表</li>
                </ol>
            </div>
        </div>

        <div class="col-sm-12" style="margin-top: -20px">
            <div style="margin-right: 0;margin-left: auto">
                <form method="post"
                      action="{% url 'script:scripts-search' %}?project_id={{ request.tracer.project.id }}"
                      style="transform: scale(1.0)">
                    {% csrf_token %}
                    <div class="col-lg-6">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="输入工具名来模糊查找" name="q"
                                   style="width: 200px">
                            <input type="submit" value="工具查找" class="btn btn-default" style="margin-left: -5px">


                            <a href="{% url 'script:scripts-add' %}?project_id={{ request.tracer.project.id }}"
                               class="btn btn-default"
                               style="margin-left: 2px;color: #333">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                新建工具</a>


                            <a href="{% url 'script:scripts-auto-add' %}?project_id={{ request.tracer.project.id }}"
                               class="btn btn-default" style="margin-left: 2px;color: #333">
                                <span class="glyphicon glyphicon-cloud-upload" aria-hidden="true"></span>
                                工具录入</a>

                            {% if scripts_obj %}

                                <a href="{% url 'script:scripts-export-output' %}?project_id={{ request.tracer.project.id }}"
                                   class="btn btn-default" style="margin-left: 2px;color: #333">
                                    <span class="glyphicon glyphicon-share" aria-hidden="true"></span>
                                    导出</a>

                            {% endif %}

                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="panel-heading">
                <div class="panel-body">
                    {% if categroy_count %}
                        {% for category in categroy_count %}
                            <a class="btn btn-default btn-sm"
                               style="font-size: 15px;margin-left: 5px;color: black;margin-top: 10px"
                               href="{% url 'script:scripts-category-search' %}?project_id={{ request.tracer.project.id }}&category_id={{ category.category.id }}">
                                {{ category.category.name }} <span class="badge"
                                                                   style="background-color: #337ab7">{{ category.count }}</span>
                            </a>
                        {% endfor %}
                    {% endif %}

                    {% if categroy_count %}
                        <a class="btn btn-default btn-sm"
                           style="font-size: 15px;margin-left: 5px;color: black;margin-top: 10px"
                           data-toggle="modal"
                           data-target="#AddGroupModel"
                           onclick="">
                            <span class="glyphicon glyphicon-plus"></span>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            {% if tool_category_count %}
                <div>
                    <div class="panel-body">

                        {% for foo in tool_category_count %}
                            <div class="item" style="margin-left: 30px">

                                <div style="height: 30px;text-align: center;padding: 10px 10px;color: #8c8c8c;background-color: #f5f5f5;overflow: scroll">
                                    <span title="{{ foo.title }}">{{ foo.title }}</span>
                                </div>

                                <a href="{% url 'script:scripts-detail' %}?project_id={{ request.tracer.project.id }}&script_id={{ foo.id }}"
                                   class="title">
                                    <img src="{{ foo.showImage }}" alt="">
                                </a>

                                <hr>

                                <div style="height: 30px;padding: 10px 10px;color: #8c8c8c;overflow: scroll">
                                    {% if foo.desc %}
                                        <span title="{{ foo.desc }}"><small>说明：{{ foo.desc }}</small></span>
                                    {% else %}
                                        <span title="{{ foo.desc }}"><small>说明：暂无说明</small></span>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            {% else %}
                <div style="height:calc(100vh - 100px)">
                    <div style="text-align: center;margin-top: 200px">
                            <span style="text-align: center;font-size: 15px">暂无工具，请点击
                            <a class="btn btn-default btn-sm" style="color: #333"
                               href="{% url 'script:scripts-add' %}?project_id={{ request.tracer.project.id }}"><span
                                    class="glyphicon glyphicon-plus"
                                    aria-hidden="true"></span> 新建工具</a>
                                创建
                            </span>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    {#    增加分类#}
    <div class="modal fade" id="AddGroupModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h2 class="modal-title" id="myModalLabel">添加分组</h2>
                </div>
                <div class="modal-body">
                    <form id="editForm">
                        <div>
                            <div class="form-group">
                                <input type="text" hidden value="" id="file_id">
                                <h3>分组名称:</h3>
                                <input type="text" class="form-control" id="category_name" style="margin-top: 3px"
                                       value="">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="AddGroupBTN" type="button" class="btn btn-primary">添 加</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
        $(function () {
            $("#AddGroupBTN").click(function () {
                var category_name = $("#category_name").val();

                if (category_name === "") {
                    alert("【分类名称】不能为空！");
                    return false;
                }

                $.ajax({
                    url: "{% url 'script:scripts-category-add' %}",
                    type: "POST",
                    dataType: 'json',
                    data: {
                        'category_name': category_name,
                        'project_id': {{ request.tracer.project.id }},
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (data) {
                        if (data.status) {
                            alert(data.data)
                            location.href = '{% url 'script:scripts-all' %}?project_id={{ request.tracer.project.id }}'
                        } else {
                            alert(data.data)
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}